package com.humanless.neuron.dji;

/**
 * DJI drone states.
 */
public enum DjiDroneState {
    PRODUCT_NAME,
    PRODUCT_REGISTRATION,
    PRODUCTION_CONNECTION,

    // States
    AIRCRAFT_RETURNING_HOME,
    AIRCRAFT_FAIL_SAFE,
    AIRCRAFT_HOME_LOCATION,
    AIRCRAFT_IMU_PREHEATING,
    AIRCRAFT_MULTI_MODE_OPEN,
    AIRCRAFT_LIMITED_HEIGHT_REACHED,
    AIRCRAFT_LIMITED_RADIUS_REACHED,
    AIRCRAFT_ULTRASONIC,
    AIRCRAFT_ULTRASONIC_ERROR,
    AIRCRAFT_VISION_SENSOR,
    AIRCRAFT_FLYING,
    AIRCRAFT_HOME_LOCATION_LATITUDE,
    AIRCRAFT_HOME_LOCATION_LONGITUDE,
    AIRCRAFT_LOCATION_LATITUDE,
    AIRCRAFT_LOCATION_LONGITUDE,
    AIRCRAFT_LOCATION_ALTITUDE,
    AIRCRAFT_VELOCITY_X,
    AIRCRAFT_VELOCITY_Y,
    AIRCRAFT_VELOCITY_Z,

    // Diagnostic
    AIRCRAFT_DIAGNOSTICS,

    // Remote
    CONTROLLER_SIGNAL,

    // Battery
    BATTERY_ENERGY_REMAINING_PERCENT,
    BATTERY_TEMPERATURE,
    BATTERY_CURRENT,
    BATTERY_ENERGY,
    BATTERY_VOLTAGE,
    BATTERY_TOTAL_ENERGY,
    BATTERY_LIFETIME_REMAINING_PERCENT,
    BATTERY_DISCHARGE_COUNT,
    BATTERY_CHARGING,

    // Camera
    CAMERA_NAME,
    CAMERA_SERIAL,
    CAMERA_MODE,
    CAMERA_RECORDING_TIME,
    CAMERA_ERROR,
    CAMERA_OVER_HEAT,
    CAMERA_RECORDING,
    CAMERA_SHOOTING_BURST_PHOTO,
    CAMERA_SHOOTING_INTERVAL_PHOTO,
    CAMERA_SHOOTING_SINGLE_PHOTO,
    CAMERA_SHOOTING_SINGLE_PHOTO_RAW,
    CAMERA_STORING_PHOTO,
    CAMERA_USB_MODE,

    // Camera exposure
    CAMERA_APERTURE,
    CAMERA_EXPOSURE_COMPENSATION,
    CAMERA_ISO,
    CAMERA_SHUTTER_SPEED,

    // Media
    CAMERA_MEDIA,
}
