package com.humanless.neuron.dji;

/**
 * DJI drone events.
 */
public enum DjiDroneEvent {
    PRODUCT_REGISTRATION,
    PRODUCT_CHANGE,
    PRODUCT_COMPONENT_CHANGE,
    PRODUCT_CONNECTION_CHANGE,

    AIRCRAFT_STATE_CHANGE,
    AIRCRAFT_TAKE_OFF,
    AIRCRAFT_LAND,
    AIRCRAFT_DIAGNOSTIC,

    BATTERY_STATE_CHANGE,

    CAMERA_STATE_CHANGE,
    CAMERA_EXPOSURE_CHANGE,
    CAMERA_VIDEO_FEED,
    CAMERA_MEDIA,

    CONTROLLER_SIGNAL_CHANGE,
}
