package com.humanless.neuron.dji;

/**
 * DJI drone events.
 */
public enum DjiDroneEvent {
    REGISTRATION,
    PRODUCT_CHANGE,
    COMPONENT_CHANGE,
    PRODUCT_CONNECTION_CHANGE,
    FLIGHT_STATE_CHANGE,
    BATTERY_STATE_CHANGE,
    CAMERA_STATE_CHANGE,
    CAMERA_EXPOSURE_CHANGE,
    CAMERA_VIDEO_FEED,
    CAMERA_MEDIA,
    DIAGNOSTIC,
    TAKE_OFF,
    LAND,
}
