package com.humanless.neuron.dji;

/**
 * DJI drone states.
 */
public enum DjiDroneState {
    PRODUCT_NAME,
    REGISTRATION,
    CAMERA_NAME,
    CAMERA_SERIAL,
    PRODUCTION_CONNECTION,
    RETURNING_HOME,
    BATTERY_LEVEL,
    FLYING,
    HOME_LOCATION_LATITUDE,
    HOME_LOCATION_LONGITUDE,
    AIRCRAFT_LOCATION_LATITUDE,
    AIRCRAFT_LOCATION_LONGITUDE,
    AIRCRAFT_LOCATION_ALTITUDE,
    VELOCITY_X,
    VELOCITY_Y,
    VELOCITY_Z,
}
