package com.humanless.neuron.dji;

/**
 * DJI drone states.
 */
public enum DjiDroneState {
    PRODUCT_NAME,
    REGISTRATION,
    CAMERA_NAME,
    CAMERA_SERIAL,
    PRODUCTION_CONNECTION,

    // States
    RETURNING_HOME,
    FAIL_SAFE,
    HOME_LOCATION,
    IMU_PREHEATING,
    MULTI_MODE_OPEN,
    LIMITED_HEIGHT_REACHED,
    LIMITED_RADIUS_REACHED,
    ULTRASONIC,
    ULTRASONIC_ERROR,
    VISION_SENSOR,
    FLYING,
    HOME_LOCATION_LATITUDE,
    HOME_LOCATION_LONGITUDE,
    AIRCRAFT_LOCATION_LATITUDE,
    AIRCRAFT_LOCATION_LONGITUDE,
    AIRCRAFT_LOCATION_ALTITUDE,
    VELOCITY_X,
    VELOCITY_Y,
    VELOCITY_Z,

    // Battery
    BATTERY_ENERGY_REMAINING_PERCENT,
    BATTERY_TEMPERATURE,
    BATTERY_CURRENT,
    BATTERY_ENERGY,
    BATTERY_VOLTAGE,
    BATTERY_TOTAL_ENERGY,
    BATTERY_LIFETIME_REMAINING_PERCENT,
    BATTERY_DISCHARGE_COUNT,
    BATTERY_CHARGING,

    // Camera
    CAMERA_MODE,
    CAMERA_RECORDING_TIME,
    CAMERA_ERROR,
    CAMERA_OVER_HEAT,
    CAMERA_RECORDING,
    CAMERA_SHOOTING_BURST_PHOTO,
    CAMERA_SHOOTING_INTERVAL_PHOTO,
    CAMERA_SHOOTING_SINGLE_PHOTO,
    CAMERA_SHOOTING_SINGLE_PHOTO_RAW,
    CAMERA_STORING_PHOTO,
    CAMERA_USB_MODE,
}
